// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQM2ebpGQSj08C3UlWu-rSBMtB_3nLyqM',
    appId: '1:649340860696:web:ffda882f70df7b8dc1066d',
    messagingSenderId: '649340860696',
    projectId: 'redbits-ch',
    authDomain: 'redbits-ch.firebaseapp.com',
    storageBucket: 'redbits-ch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtd4W0y7JOUa7RQteyiemJMyUp-qSkis',
    appId: '1:649340860696:android:4e9a199442bd05b0c1066d',
    messagingSenderId: '649340860696',
    projectId: 'redbits-ch',
    storageBucket: 'redbits-ch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssm66jGQPBQYijBmabu0lxLs_VBzCATU',
    appId: '1:649340860696:ios:473099e3c4c8ebdec1066d',
    messagingSenderId: '649340860696',
    projectId: 'redbits-ch',
    storageBucket: 'redbits-ch.firebasestorage.app',
    iosBundleId: 'com.example.redbits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDssm66jGQPBQYijBmabu0lxLs_VBzCATU',
    appId: '1:649340860696:ios:473099e3c4c8ebdec1066d',
    messagingSenderId: '649340860696',
    projectId: 'redbits-ch',
    storageBucket: 'redbits-ch.firebasestorage.app',
    iosBundleId: 'com.example.redbits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQM2ebpGQSj08C3UlWu-rSBMtB_3nLyqM',
    appId: '1:649340860696:web:c256ce8fb9fb84cdc1066d',
    messagingSenderId: '649340860696',
    projectId: 'redbits-ch',
    authDomain: 'redbits-ch.firebaseapp.com',
    storageBucket: 'redbits-ch.firebasestorage.app',
  );
}
